### ISSUE TITLE
Unwatchable video in The Pomodoro Technique

### ISSUE THREAD

**Issue by maxolasersquad** [joebew42/study-path#1]
http://pomodorotechnique.com/ embeds a Vimeo video that simply shows, "Sorry Because of its privacy settings, this video cannot be played here."

**Comment by joebew42** [comment]
Hi, thank you for reporting the issue: I've already notified Pomodoro Technique staff: https://twitter.com/joebew42/status/700593628834504704

Btw, I can watch the video. Maybe is a problem of settings. The author should be able to resolve this. Hoping for an answer :)
