### ISSUE TITLE
Missing license 

### ISSUE THREAD

**Issue by waterlink** [joebew42/study-path#9]
Under which license this is released? Without license specified nobody can use that information for teaching anyone, except for the author. 

I am not sure which license would suite it better, maybe one of Creative Commons..

**Comment by joebew42** [comment]
Hi @waterlink ,

Thank you for submitting this issue,

I totally forgot to choose a license. I think that a **CC BY-SA** would fit well, what do you think?

**Comment by waterlink** [comment]
@joebew42 CC BY-SA sounds good!
